---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aavgodes/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -f index.html $DEPLOYPATH/index.html
    - /bin/cp -f styles.css $DEPLOYPATH/styles.css
    - /bin/cp -f script.js $DEPLOYPATH/script.js
